-- AlterTable
ALTER TABLE "companies" ADD COLUMN     "business_address" TEXT,
ADD COLUMN     "business_description" TEXT,
ADD COLUMN     "business_name" TEXT,
ADD COLUMN     "business_phone_number" TEXT,
ADD COLUMN     "business_proof_of_address" TEXT,
ADD COLUMN     "business_type" TEXT,
ADD COLUMN     "business_website" TEXT,
ADD COLUMN     "country_of_operation" TEXT,
ADD COLUMN     "incorporation_certificate" TEXT,
ADD COLUMN     "memart" TEXT,
ADD COLUMN     "share_holding_document" TEXT,
ADD COLUMN     "source_of_funds" TEXT,
ADD COLUMN     "step" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "tax_id_number" TEXT,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "client_id" DROP NOT NULL,
ALTER COLUMN "client_key" DROP NOT NULL;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "city" TEXT,
ADD COLUMN     "country_of_residence" TEXT,
ADD COLUMN     "first_name" TEXT,
ADD COLUMN     "gender" TEXT,
ADD COLUMN     "id_document_back" TEXT,
ADD COLUMN     "id_document_front" TEXT,
ADD COLUMN     "id_document_type" TEXT,
ADD COLUMN     "id_number" TEXT,
ADD COLUMN     "last_name" TEXT,
ADD COLUMN     "nationality" TEXT,
ADD COLUMN     "phone_number" TEXT,
ADD COLUMN     "postal_code" TEXT,
ADD COLUMN     "proof_of_address" TEXT,
ADD COLUMN     "role_in_company" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "street" TEXT;
